name: First Pipeline

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Show Files
        run: ls

      - name: Print Message
        run: echo "Sagar welcome to GitHub"
