name: Auto Pipeline

name: Auto Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: echo "Pipeline triggered by git push"

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
  - uses: action/checkout@v3

  - runs-on: echo "sagar pipeline is run" 
